<a href="https://colab.research.google.com/github/UKD1211/Tier_N_Supplier_Visibility_Risk_Pred/blob/main/country_risk_1_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_excel('/content/P_NP Country Risk perso assessment.xlsx')

In [17]:
df.sample(10)

,Time,Time Code,Country Name,Country Code,GDP growth (annual %) [NY.GDP.MKTP.KD.ZG],GDP per capita growth (annual %) [NY.GDP.PCAP.KD.ZG],Bank liquid reserves to bank assets ratio (%) [FD.RES.LIQU.AS.ZS],"Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]","Interest rate spread (lending rate minus deposit rate, %) [FR.INR.LNDP]",Real interest rate (%) [FR.INR.RINR],"Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]",Research and development expenditure (% of GDP) [GB.XPD.RSDV.GD.ZS],"Central government debt, total (% of GDP) [GC.DOD.TOTL.GD.ZS]",Control of Corruption: Estimate [CC.EST],Government Effectiveness: Estimate [GE.EST],Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST],Rule of Law: Estimate [RL.EST],"Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]"
221,2020,YR2020,Andorra,AND,-11.18394,-12.223838,..,..,..,..,..,..,..,1.265454,1.749241,1.588675,1.615182,..
699,2022,YR2022,Croatia,HRV,7.294453,7.943957,..,10.780581,..,..,..,1.40323,..,0.147807,0.581314,0.672563,0.367797,6.811
822,2022,YR2022,Singapore,SGP,4.108,0.719822,..,6.130954,..,..,..,..,154.103643,2.0947,2.144236,1.440372,1.77819,3.591
177,2019,YR2019,South Africa,ZAF,0.259936,-1.380361,3.386052,4.102851,3.116667,5.268416,3.041667,0.61304,64.589278,-0.031281,0.127971,-0.283221,-0.188337,28.468
159,2019,YR2019,Qatar,QAT,0.688256,-1.522022,5.541056,-0.666641,1.412602,9.937847,..,..,..,0.817295,0.707393,0.68437,0.70765,0.1
828,2022,YR2022,South Africa,ZAF,2.058137,0.625217,3.886957,7.039873,3.725,3.373876,3.644167,0.61729,76.205443,-0.330095,-0.109028,-0.681386,0.040775,33.268
620,2021,YR2021,Suriname,SUR,-2.435386,-3.316299,71.350621,59.119663,8.024601,-29.113782,..,..,..,-0.418558,-0.680693,0.348392,-0.126214,8.706
132,2019,YR2019,Montenegro,MNE,4.393916,4.341448,22.309836,0.361564,5.71455,4.108971,5.640833,0.36328,..,-0.030203,0.106434,0.058069,-0.007429,15.128
319,2020,YR2020,Kiribati,KIR,-1.468055,-3.169913,..,2.553246,..,..,..,..,..,0.467279,0.134627,1.157592,1.011369,..
637,2021,YR2021,Ukraine,UKR,3.445621,4.410509,24.357701,9.363139,8.657167,-9.224527,..,0.38478,..,-0.787212,-0.439536,-1.126984,-0.681738,9.834

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1090 entries, 0 to 1089
Data columns (total 18 columns):
 #   Column                                                                                Non-Null Count  Dtype
---  ------                                                                                --------------  -----
 0   Time                                                                                  1087 non-null   object
 1   Time Code                                                                             1085 non-null   object
 2   Country Name                                                                          1085 non-null   object
 3   Country Code                                                                          1085 non-null   object
 4   GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]                                             1085 non-null   object
 5   GDP per capita growth (annual %) [NY.GDP.PCAP.KD.ZG]                                  1085 non-null   object
 6   Bank liquid reserves to bank assets ratio (%) [FD.RES.LIQU.AS.ZS]                     1085 non-null   object
 7   Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]                                1085 non-null   object
 8   Interest rate spread (lending rate minus deposit rate, %) [FR.INR.LNDP]               1085 non-null   object
 9   Real interest rate (%) [FR.INR.RINR]                                                  1085 non-null   object
 10  Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]      1085 non-null   object
 11  Research and development expenditure (% of GDP) [GB.XPD.RSDV.GD.ZS]                   1085 non-null   object
 12  Central government debt, total (% of GDP) [GC.DOD.TOTL.GD.ZS]                         1085 non-null   object
 13  Control of Corruption: Estimate [CC.EST]                                              1085 non-null   object
 14  Government Effectiveness: Estimate [GE.EST]                                           1085 non-null   object
 15  Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST]              1085 non-null   object
 16  Rule of Law: Estimate [RL.EST]                                                        1085 non-null   object
 17  Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]  1085 non-null   object
dtypes: object(18)
memory usage: 153.4+ KB

In [19]:
df = df[['Time','Country Name','Control of Corruption: Estimate [CC.EST]', 'Government Effectiveness: Estimate [GE.EST]', 'Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST]','Rule of Law: Estimate [RL.EST]','Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]', 'Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]', 'Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]']]

In [20]:
df

,Time,Country Name,Control of Corruption: Estimate [CC.EST],Government Effectiveness: Estimate [GE.EST],Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST],Rule of Law: Estimate [RL.EST],"Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]","Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]","Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]"
0,2019,Afghanistan,-1.41931,-1.519113,-2.65254,-1.7421,2.302373,11.187,..
1,2019,Albania,-0.564274,-0.062301,0.110105,-0.426317,1.411091,11.466,..
2,2019,Algeria,-0.65617,-0.567921,-1.055854,-0.861034,1.951768,12.302,5.095833
3,2019,American Samoa,1.780229,0.489977,1.144934,1.268202,..,..,..
4,2019,Andorra,1.176189,1.851921,1.577367,1.510215,..,..,..
...,...,...,...,...,...,...,...,...,...
1085,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1088,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1089,Last Updated: 02/24/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df.isnull().sum()

Time                                                                                    3
Country Name                                                                            5
Control of Corruption: Estimate [CC.EST]                                                5
Government Effectiveness: Estimate [GE.EST]                                             5
Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST]                5
Rule of Law: Estimate [RL.EST]                                                          5
Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]                                  5
Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]    5
Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]        5
dtype: int64

In [22]:
df = df.dropna()

In [23]:
df.iloc[4,:]

Time                                                                                        2019
Country Name                                                                             Andorra
Control of Corruption: Estimate [CC.EST]                                                1.176189
Government Effectiveness: Estimate [GE.EST]                                             1.851921
Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST]                1.577367
Rule of Law: Estimate [RL.EST]                                                          1.510215
Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]                                        ..
Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]          ..
Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]              ..
Name: 4, dtype: object

In [24]:
df['Country Name'].value_counts()

Country Name
Afghanistan              5
Albania                  5
Algeria                  5
American Samoa           5
Andorra                  5
                        ..
Virgin Islands (U.S.)    5
West Bank and Gaza       5
Yemen, Rep.              5
Zambia                   5
Zimbabwe                 5
Name: count, Length: 217, dtype: int64

In [25]:
df['Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]'] = df['Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]'].replace('..', np.nan).astype(float)
df.groupby('Country Name')['Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]'].mean()

/tmp/ipykernel_17295/1380793503.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]'] = df['Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]'].replace('..', np.nan).astype(float)
/tmp/ipykernel_17295/1380793503.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]'] = df['Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]'].replace('..', np.nan).astype(float)

Country Name
Afghanistan                    NaN
Albania                   4.553194
Algeria                   5.023333
American Samoa                 NaN
Andorra                        NaN
                           ...
Virgin Islands (U.S.)          NaN
West Bank and Gaza             NaN
Yemen, Rep.                    NaN
Zambia                  -11.080353
Zimbabwe                       NaN
Name: Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK], Length: 217, dtype: float64

In [30]:
df.drop(columns = ['Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]'], inplace = True)

/tmp/ipykernel_17295/1284948720.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns = ['Risk premium on lending (lending rate minus treasury bill rate, %) [FR.INR.RISK]'], inplace = True)

In [31]:
df

,Time,Country Name,Control of Corruption: Estimate [CC.EST],Government Effectiveness: Estimate [GE.EST],Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST],Rule of Law: Estimate [RL.EST],"Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]","Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]"
0,2019,Afghanistan,-1.41931,-1.519113,-2.65254,-1.7421,2.302373,11.187
1,2019,Albania,-0.564274,-0.062301,0.110105,-0.426317,1.411091,11.466
2,2019,Algeria,-0.65617,-0.567921,-1.055854,-0.861034,1.951768,12.302
3,2019,American Samoa,1.780229,0.489977,1.144934,1.268202,..,..
4,2019,Andorra,1.176189,1.851921,1.577367,1.510215,..,..
...,...,...,...,...,...,...,...,...
1080,2023,Virgin Islands (U.S.),-0.018457,0.654168,0.534723,0.948083,..,11.358
1081,2023,West Bank and Gaza,-0.676134,-1.209557,-1.865219,-0.682805,5.871102,..
1082,2023,"Yemen, Rep.",-1.648933,-2.27542,-2.562939,-1.838976,..,16.944
1083,2023,Zambia,-0.477707,-0.65897,0.201727,-0.529127,10.884532,5.861
1084,2023,Zimbabwe,-1.261216,-1.170335,-0.934447,-1.277143,..,9.348

In [38]:
df = df[(df['Time'] == 2021) | (df['Time'] == 2022) | (df['Time'] == 2023)]

In [41]:
df.replace("..", np.nan, inplace=True)

/tmp/ipykernel_17295/1521653289.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("..", np.nan, inplace=True)
/tmp/ipykernel_17295/1521653289.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace("..", np.nan, inplace=True)

In [42]:
df

,Time,Country Name,Control of Corruption: Estimate [CC.EST],Government Effectiveness: Estimate [GE.EST],Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST],Rule of Law: Estimate [RL.EST],"Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]","Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]"
434,2021,Afghanistan,-1.152266,-1.670588,-2.518676,-1.877234,5.133203,12.006
435,2021,Albania,-0.577180,-0.035985,0.196372,-0.280716,2.041472,11.474
436,2021,Algeria,-0.635961,-0.652746,-0.992457,-0.833023,7.226063,13.656
437,2021,American Samoa,1.279687,0.638740,1.066841,1.138760,NaN,NaN
438,2021,Andorra,1.279687,1.748928,1.581259,1.642051,NaN,NaN
...,...,...,...,...,...,...,...,...
1080,2023,Virgin Islands (U.S.),-0.018457,0.654168,0.534723,0.948083,NaN,11.358
1081,2023,West Bank and Gaza,-0.676134,-1.209557,-1.865219,-0.682805,5.871102,NaN
1082,2023,"Yemen, Rep.",-1.648933,-2.275420,-2.562939,-1.838976,NaN,16.944
1083,2023,Zambia,-0.477707,-0.658970,0.201727,-0.529127,10.884532,5.861
1084,2023,Zimbabwe,-1.261216,-1.170335,-0.934447,-1.277143,NaN,9.348

In [44]:
df.isnull().sum()

Time                                                                                      0
Country Name                                                                              0
Control of Corruption: Estimate [CC.EST]                                                 36
Government Effectiveness: Estimate [GE.EST]                                              36
Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST]                 36
Rule of Law: Estimate [RL.EST]                                                           36
Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]                                  119
Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]     94
dtype: int64

In [48]:
for cols in df.columns[2:]:
  df.loc[:, cols] = df[cols].fillna(df[cols].median())

/tmp/ipykernel_17295/2855724750.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols].fillna(df[cols].median(),inplace = True)
/tmp/ipykernel_17295/2855724750.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[cols].fillna(df[cols].median(),inplace = True)

In [49]:
df

,Time,Country Name,Control of Corruption: Estimate [CC.EST],Government Effectiveness: Estimate [GE.EST],Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST],Rule of Law: Estimate [RL.EST],"Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]","Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]"
434,2021,Afghanistan,-1.152266,-1.670588,-2.518676,-1.877234,5.133203,12.006
435,2021,Albania,-0.577180,-0.035985,0.196372,-0.280716,2.041472,11.474
436,2021,Algeria,-0.635961,-0.652746,-0.992457,-0.833023,7.226063,13.656
437,2021,American Samoa,1.279687,0.638740,1.066841,1.138760,5.674653,5.415
438,2021,Andorra,1.279687,1.748928,1.581259,1.642051,5.674653,5.415
...,...,...,...,...,...,...,...,...
1080,2023,Virgin Islands (U.S.),-0.018457,0.654168,0.534723,0.948083,5.674653,11.358
1081,2023,West Bank and Gaza,-0.676134,-1.209557,-1.865219,-0.682805,5.871102,5.415
1082,2023,"Yemen, Rep.",-1.648933,-2.275420,-2.562939,-1.838976,5.674653,16.944
1083,2023,Zambia,-0.477707,-0.658970,0.201727,-0.529127,10.884532,5.861
1084,2023,Zimbabwe,-1.261216,-1.170335,-0.934447,-1.277143,5.674653,9.348

In [54]:
x1 = df.groupby('Country Name')['Control of Corruption: Estimate [CC.EST]'].mean().values
x2 = df.groupby('Country Name')['Government Effectiveness: Estimate [GE.EST]'].mean().values
x3 = df.groupby('Country Name')['Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST]'].mean().values
x4 = df.groupby('Country Name')['Rule of Law: Estimate [RL.EST]'].mean().values
x5 = df.groupby('Country Name')['Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]'].mean().values
x6 = df.groupby('Country Name')['Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]'].mean().values

In [56]:
df_countries = pd.DataFrame(np.column_stack([x1,x2,x3,x4,x5,x6]),
                            columns = df.columns[2:],
                            index = df.groupby('Country Name')['Control of Corruption: Estimate [CC.EST]'].mean().index)

In [65]:
df_countries

,Control of Corruption: Estimate [CC.EST],Government Effectiveness: Estimate [GE.EST],Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST],Rule of Law: Estimate [RL.EST],"Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]","Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]"
Country Name,,,,,,
Afghanistan,-1.163627,-1.845879,-2.515904,-1.728907,4.733532,13.371333
Albania,-0.439196,0.093137,0.161994,-0.203466,4.508340,10.976000
Algeria,-0.621104,-0.612127,-0.740332,-0.781549,8.604584,12.561000
American Samoa,1.267105,0.653512,1.101412,1.190789,5.674653,5.415000
Andorra,1.267105,1.573209,1.583571,1.534811,5.674653,5.415000
...,...,...,...,...,...,...
Virgin Islands (U.S.),-0.009413,0.653512,0.513600,0.930649,5.674653,12.319333
West Bank and Gaza,-0.713436,-0.969545,-1.801366,-0.583556,3.616602,18.741667
"Yemen, Rep.",-1.665808,-2.278195,-2.535378,-1.831755,5.674653,17.493333
Zambia,-0.580120,-0.712657,0.138491,-0.550842,14.632834,5.683667
Zimbabwe,-1.266111,-1.237373,-0.927955,-1.265431,69.641976,9.658333